#pragma warning(push)
#pragma warning(disable:4505)

#include <MiniMPL/addRemove.hpp> 
#include <MiniMPL/anyObject.hpp> 
#include <MiniMPL/any_cast.hpp> 
#include <MiniMPL/arrayTrait.hpp> 
#include <MiniMPL/atomic_counter.h> 
#include <MiniMPL/binaryFunction.hpp> 
#include <MiniMPL/bitsetEnum.hpp> 
#include <MiniMPL/callbacker.hpp> 
#include <MiniMPL/classObjectCreater.hpp> 
#include <MiniMPL/classRegister.hpp> 
#include <MiniMPL/classRegisterMacro.hpp> 
#include <MiniMPL/classRegisterMacro_MSVC.hpp> 
#include <MiniMPL/collector.hpp> 
#include <MiniMPL/comparer.hpp> 
#include <MiniMPL/container.hpp> 
#include <MiniMPL/containerInitializer.hpp> 
#include <MiniMPL/convert_enable_if.hpp> 
#include <MiniMPL/enumTrait.hpp> 
#include <MiniMPL/fromToString.hpp> 
#include <MiniMPL/functionParams.hpp> 
#include <MiniMPL/hasXXX.hpp> 
#include <MiniMPL/isXXX.hpp> 
#include <MiniMPL/isXXXEx.hpp> 
#include <MiniMPL/kitType.hpp> 
#include <MiniMPL/libConfig.h> 
#include <MiniMPL/macroDef.h> 
#include <MiniMPL/macro_assert.h> 
#include <MiniMPL/macro_class.h> 
#include <MiniMPL/macro_init.h> 
#include <MiniMPL/macro_longJump.h> 
#include <MiniMPL/macro_Loop.hpp> 
#include <MiniMPL/macro_makeTxt.h> 
#include <MiniMPL/macro_makeVar.h> 
#include <MiniMPL/macro_traceLog.h> 
#include <MiniMPL/matchTypeLocater.hpp> 
#include <MiniMPL/memberPtr.hpp> 
#include <MiniMPL/paramPack.hpp> 
#include <MiniMPL/paramPackageCall.hpp> 
#include <MiniMPL/paramPackShift.hpp> 
#include <MiniMPL/placeHolder.hpp> 
#include <MiniMPL/platformEnv.h> 
#include <MiniMPL/pointer2value.hpp> 
#include <MiniMPL/productSpecialDef.h> 
#include <MiniMPL/sameQualifier.hpp> 
#include <MiniMPL/scanPrint.hpp> 
#include <MiniMPL/smartPointer.hpp> 
#include <MiniMPL/stdAlgorithmEx.hpp> 
#include <MiniMPL/swap.hpp> 
#include <MiniMPL/tester.hpp> 
#include <MiniMPL/traverseCallbackMacro.hpp> 
#include <MiniMPL/traverseTypeContainer.hpp> 
#include <MiniMPL/typeList.hpp> 
#include <MiniMPL/typeListMacro.hpp> 
#include <MiniMPL/typeLogic.hpp> 
#include <MiniMPL/unaryFunction.hpp> 
#include <MiniMPL/unaryFunctionAssemble.hpp> 
#include <MiniMPL/unaryFunctionCreater.hpp> 
#include <MiniMPL/unaryFunctionParams.hpp> 
#include <MiniMPL/unaryFunctionParamTransfer.hpp> 
#include <MiniMPL/valueCompare.hpp> 
#include <MiniMPL/vldFix.h> 

#pragma warning(pop)
